spring:
  application:
    name: petmilyFinalFinalRealFinal
  # DB 설정
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB 연결 타임아웃 30초 설정
    hikari:
      connection-timeout: 30000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 215MB
      location: $(java.io.tmpdir)
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

# mybatis 설정
mybatis:
  type-aliases-package: com.petmily.mapperInterface
  mapper-locations: classpath:/mapper/*.xml