spring:
  application:
    name: petmilyFinalFinalRealFinal
  # DB 설정
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # jsp 경로 설정
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 215MB
      location: $(java.io.tmpdir)
  # JSP 사용을 위해 타임리프 차단
#  thymeleaf:
#    enabled: false
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

# mybatis 설정
mybatis:
  type-aliases-package: com.petmily.mapperInterface
  mapper-locations: classpath:/mapper/*.xml
