spring:
  application:
    name: petmilyReal
  # DB 설정
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB 연결 타임아웃 30초 설정
    hikari:
      connection-timeout: 30000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 215MB
      location: $(java.io.tmpdir)
  # 탬플릿 캐시 비활성화
  thymeleaf:
    cache : false
  # 타임리프 경로 설정
    prefix : classpath:/templates/
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

# 세션
server:
  servlet:
     session:
       # 세션 타임아웃 설정 (30분)
       timeout : 30m
       # 세션 지속 설정
       persistent : true

# mybatis 설정
mybatis:
  type-aliases-package: com.petmily.mapperInterface
  mapper-locations: classpath:/mapper/*.xml