name : Web hosting

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with: 
          ref: ${{ github.ref }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with: 
          java-version: '17'
          distribution: 'temurin'

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Docker build and publish
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.APP_NAME }}:${{ github.ref_name }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.APP_NAME }}:${{ github.ref_name }}
